#!/usr/bin/env python3
"""amalgamate.py - generate single_include/stego_all.h (stb-style).

Usage: amalgamate.py [out.h]
Concatenates include/stego/*.h + src/*.cpp with #include "stego/*"
lines stripped (replaced by this file's own declarations section).
Usage in consumer: #define STEGO_IMPLEMENTATION in exactly one TU.
"""
import os
import sys

ROOT = os.path.dirname(os.path.abspath(__file__))
OUT = sys.argv[1] if len(sys.argv) > 1 else os.path.join(
    ROOT, 'single_include', 'stego_all.h')


def read(p):
    with open(p, encoding='utf-8') as f:
        return f.read()


parts = []
parts.append('// stego_all.h - amalgamated single-header distribution.')
parts.append('// Generated by amalgamate.py - do not edit directly.')
parts.append('// #define STEGO_IMPLEMENTATION in exactly one translation unit.')
parts.append('#pragma once')
parts.append('#include <stdint.h>\n#include <stddef.h>\n#include <string>\n#include <vector>\n#include <random>\n#include <string.h>')

for name in ['format.h', 'stego.h', 'stego_c.h']:
    body = read(os.path.join(ROOT, 'include', 'stego', name))
    body = '\n'.join(l for l in body.splitlines()
                     if not l.strip().startswith('#pragma once')
                     and not l.strip().startswith('#include <')
                     and '#include "stego/' not in l)
    parts.append(f'// ---- {name} ----\n' + body)

parts.append('#ifdef STEGO_IMPLEMENTATION')
for name in ['sha256.cpp', 'codec.cpp', 'api.cpp']:
    body = read(os.path.join(ROOT, 'src', name))
    body = '\n'.join(l for l in body.splitlines()
                     if '#include "stego/' not in l
                     and not l.strip().startswith('#include <string')
                     and not l.strip().startswith('#include <vector')
                     and not l.strip().startswith('#include <string.h')
                     and not l.strip().startswith('#include <random>'))
    parts.append(f'// ---- {name} ----\n' + body)
parts.append('#endif // STEGO_IMPLEMENTATION')

os.makedirs(os.path.dirname(OUT), exist_ok=True)
with open(OUT, 'w', encoding='utf-8', newline='\n') as f:
    f.write('\n'.join(parts) + '\n')
print(f'[amalgamate] -> {OUT}')
