// stego_all.h — amalgamated single-header distribution.
// Generated by amalgamate.py — do not edit directly.
// #define STEGO_IMPLEMENTATION in exactly one translation unit.
#pragma once
#include <stdint.h>
#include <stddef.h>
#include <string>
#include <vector>
#include <random>
#include <string.h>
// ---- format.h ----
// format.h — wire constants (mirrors docs/FORMAT.md).

#define STEGO_MAGIC_0 'S'
#define STEGO_MAGIC_1 'T'
#define STEGO_MAGIC_2 'G'
#define STEGO_MAGIC_3 '2'

// Latest WRITTEN format. Decoders additionally accept 0x0002 and legacy v1.
#define STEGO_FORMAT_VERSION 0x0003
// C ABI stability marker. A format bump MUST NOT imply an ABI bump.
#define STEGO_ABI_VERSION 0x0001

#define STEGO_HEADER_LEN 28     // v2 header bytes (legacy read path)
#define STEGO_HEADER_V3_LEN 44  // v3 header bytes (current write path)
#define STEGO_HEADER_PX 75      // header pixels reserved (v2 layout)
#define STEGO_HEADER_V3_PX 118  // header pixels reserved (v3 layout)

#define STEGO_SALT_LEN 16
#define STEGO_PBKDF2_ITER 100000
#define STEGO_PBKDF2_OUT 64     // 32 enc-key + 32 auth-key

#define STEGO_F_COMPRESS 0x0001  // reserved: encoders reject for now
#define STEGO_F_SCATTER  0x0002
#define STEGO_F_ENCRYPT  0x0004
#define STEGO_F_AUTH     0x0008

#define STEGO_HMAC_LEN 32
#define STEGO_AUTH_DOMAIN "stego-auth-v2"
// ---- stego.h ----
// stego.h — public C++ API. Operates on raw RGB buffers (no file IO;
// products convert PNG<->RGB with GDI+/PIL — see examples/gdiplus_glue.h).

namespace stego {

struct Image {
    uint32_t w = 0, h = 0;
    std::vector<uint8_t> rgb;  // w*h*3 bytes, R,G,B order
};

struct Options {
    bool compress = false;   // reserved: currently rejected (no backend)
    bool scatter = false;    // PRNG placement (seed required if true)
    uint32_t seed = 0;       // 0 = sequential layout
    std::string password;    // empty = no encryption/auth
    bool auth = false;       // HMAC (requires non-empty password)
};

// Encode payload into cover (cover pixels preserved except LSBs).
// Returns false on capacity/parameter errors. Payload plus header/CRC/HMAC
// overhead must fit in w*h*3 bits. On success `out` is a full RGB image.
bool Encode(const Image& cover, const uint8_t* payload, size_t payloadLen,
            const Options& opt, Image& out);

// Decode: tries the header (magic + header CRC), then legacy v1 layout
// (read-only deprecated path). Strict: CRC/HMAC failures return false.
bool Decode(const Image& img, const std::string& password,
            std::vector<uint8_t>& out);

// Capacity in payload bytes for given dims + options overhead estimate.
size_t Capacity(uint32_t w, uint32_t h);

// Library version string ("2.0.0").
const char* Version();

}  // namespace stego
// ---- stego_c.h ----
// stego_c.h — thin C ABI (FFI/Lua-ready). Mirrors stego.h semantics.
//
// Ownership: all inputs are borrowed (caller retains). Outputs marked
// callee-allocated MUST be released with stego_free(). Error codes are
// stable across STEGO_ABI_VERSION bumps (new codes only ever appended).

#ifdef __cplusplus
extern "C" {
#endif

#define STEGO_C_OK 0
#define STEGO_C_ERR_PARAM -1
#define STEGO_C_ERR_CAPACITY -2
#define STEGO_C_ERR_FORMAT -3
#define STEGO_C_ERR_CRC -4
#define STEGO_C_ERR_AUTH -5
#define STEGO_C_ERR_UNSUPPORTED -6  // e.g. COMPRESS flag (no backend yet)

typedef struct {
    uint32_t w, h;
    uint8_t* rgb;      // caller-owned w*h*3 buffer
} stego_image_t;

typedef struct {
    int compress;      // reserved, must be 0
    int scatter;
    uint32_t seed;
    const char* password;  // NULL/empty = none
    int auth;
} stego_options_t;

// out_rgb must hold w*h*3 bytes. Returns STEGO_C_*.
int stego_encode(const stego_image_t* cover,
                 const uint8_t* payload, size_t payload_len,
                 const stego_options_t* opt, uint8_t* out_rgb);

// out/out_len: callee mallocs (caller frees with stego_free).
int stego_decode(const stego_image_t* img, const char* password,
                 uint8_t** out, size_t* out_len);
void stego_free(void* p);
const char* stego_version(void);

#ifdef __cplusplus
}
#endif
#ifdef STEGO_IMPLEMENTATION
// ---- sha256.cpp ----
// sha256.cpp — compact SHA-256 (public-domain algorithm, FIPS 180-4).
// Verified against NIST vectors in tests/test_codec.cpp + pytest goldens.
#include <stdint.h>

namespace stego {
namespace sha {

static inline uint32_t Ror(uint32_t x, int n) { return (x >> n) | (x << (32 - n)); }

static const uint32_t K[64] = {
    0x428a2f98, 0x71374491, 0xb5c0fbcf, 0xe9b5dba5, 0x3956c25b, 0x59f111f1, 0x923f82a4, 0xab1c5ed5,
    0xd807aa98, 0x12835b01, 0x243185be, 0x550c7dc3, 0x72be5d74, 0x80deb1fe, 0x9bdc06a7, 0xc19bf174,
    0xe49b69c1, 0xefbe4786, 0x0fc19dc6, 0x240ca1cc, 0x2de92c6f, 0x4a7484aa, 0x5cb0a9dc, 0x76f988da,
    0x983e5152, 0xa831c66d, 0xb00327c8, 0xbf597fc7, 0xc6e00bf3, 0xd5a79147, 0x06ca6351, 0x14292967,
    0x27b70a85, 0x2e1b2138, 0x4d2c6dfc, 0x53380d13, 0x650a7354, 0x766a0abb, 0x81c2c92e, 0x92722c85,
    0xa2bfe8a1, 0xa81a664b, 0xc24b8b70, 0xc76c51a3, 0xd192e819, 0xd6990624, 0xf40e3585, 0x106aa070,
    0x19a4c116, 0x1e376c08, 0x2748774c, 0x34b0bcb5, 0x391c0cb3, 0x4ed8aa4a, 0x5b9cca4f, 0x682e6ff3,
    0x748f82ee, 0x78a5636f, 0x84c87814, 0x8cc70208, 0x90befffa, 0xa4506ceb, 0xbef9a3f7, 0xc67178f2
};

struct Ctx {
    uint32_t h[8];
    uint64_t total;
    uint8_t buf[64];
    size_t buflen;
};

static void Init(Ctx& c) {
    c.h[0] = 0x6a09e667; c.h[1] = 0xbb67ae85; c.h[2] = 0x3c6ef372; c.h[3] = 0xa54ff53a;
    c.h[4] = 0x510e527f; c.h[5] = 0x9b05688c; c.h[6] = 0x1f83d9ab; c.h[7] = 0x5be0cd19;
    c.total = 0;
    c.buflen = 0;
}

static void Block(Ctx& c, const uint8_t* p) {
    uint32_t w[64];
    for (int i = 0; i < 16; i++) {
        w[i] = ((uint32_t)p[i * 4] << 24) | ((uint32_t)p[i * 4 + 1] << 16) |
               ((uint32_t)p[i * 4 + 2] << 8) | (uint32_t)p[i * 4 + 3];
    }
    for (int i = 16; i < 64; i++) {
        uint32_t s0 = Ror(w[i - 15], 7) ^ Ror(w[i - 15], 18) ^ (w[i - 15] >> 3);
        uint32_t s1 = Ror(w[i - 2], 17) ^ Ror(w[i - 2], 19) ^ (w[i - 2] >> 10);
        w[i] = w[i - 16] + s0 + w[i - 7] + s1;
    }
    uint32_t a = c.h[0], b = c.h[1], c2 = c.h[2], d = c.h[3];
    uint32_t e = c.h[4], f = c.h[5], g = c.h[6], h = c.h[7];
    for (int i = 0; i < 64; i++) {
        uint32_t S1 = Ror(e, 6) ^ Ror(e, 11) ^ Ror(e, 25);
        uint32_t ch = (e & f) ^ ((~e) & g);
        uint32_t t1 = h + S1 + ch + K[i] + w[i];
        uint32_t S0 = Ror(a, 2) ^ Ror(a, 13) ^ Ror(a, 22);
        uint32_t maj = (a & b) ^ (a & c2) ^ (b & c2);
        uint32_t t2 = S0 + maj;
        h = g; g = f; f = e; e = d + t1;
        d = c2; c2 = b; b = a; a = t1 + t2;
    }
    c.h[0] += a; c.h[1] += b; c.h[2] += c2; c.h[3] += d;
    c.h[4] += e; c.h[5] += f; c.h[6] += g; c.h[7] += h;
}

static void Update(Ctx& c, const uint8_t* data, size_t len) {
    c.total += len;
    while (len) {
        size_t take = 64 - c.buflen;
        if (take > len) take = len;
        memcpy(c.buf + c.buflen, data, take);
        c.buflen += take;
        data += take;
        len -= take;
        if (c.buflen == 64) {
            Block(c, c.buf);
            c.buflen = 0;
        }
    }
}

static void Final(Ctx& c, uint8_t out[32]) {
    uint64_t bitlen = c.total * 8;
    uint8_t pad = 0x80;
    Update(c, &pad, 1);
    uint8_t zero = 0;
    while (c.buflen != 56) Update(c, &zero, 1);
    uint8_t lenb[8];
    for (int i = 0; i < 8; i++) lenb[i] = (uint8_t)(bitlen >> (56 - i * 8));
    // Feed length without disturbing total accounting manually:
    size_t save = c.total;
    Update(c, lenb, 8);
    c.total = save;
    for (int i = 0; i < 8; i++) {
        out[i * 4] = (uint8_t)(c.h[i] >> 24);
        out[i * 4 + 1] = (uint8_t)(c.h[i] >> 16);
        out[i * 4 + 2] = (uint8_t)(c.h[i] >> 8);
        out[i * 4 + 3] = (uint8_t)c.h[i];
    }
}

std::vector<uint8_t> Hash(const uint8_t* data, size_t len) {
    Ctx c;
    Init(c);
    Update(c, data, len);
    std::vector<uint8_t> out(32);
    Final(c, out.data());
    return out;
}

// CTR keystream: SHA256(pw || BE32(counter)) concatenated.
void Keystream(const std::string& pw, uint8_t* out, size_t len) {
    uint32_t ctr = 0;
    size_t pos = 0;
    while (pos < len) {
        Ctx c;
        Init(c);
        Update(c, (const uint8_t*)pw.data(), pw.size());
        uint8_t cb[4] = {(uint8_t)(ctr >> 24), (uint8_t)(ctr >> 16),
                         (uint8_t)(ctr >> 8), (uint8_t)ctr};
        Update(c, cb, 4);
        uint8_t d[32];
        Final(c, d);
        size_t take = len - pos < 32 ? len - pos : 32;
        memcpy(out + pos, d, take);
        pos += take;
        ctr++;
    }
}

// HMAC-SHA256(key, msg).
std::vector<uint8_t> Hmac(const uint8_t* key, size_t klen,
                           const uint8_t* msg, size_t mlen) {
    uint8_t kb[64] = {0};
    if (klen > 64) {
        std::vector<uint8_t> h = Hash(key, klen);
        memcpy(kb, h.data(), 32);
    } else {
        memcpy(kb, key, klen);
    }
    uint8_t ipad[64], opad[64];
    for (int i = 0; i < 64; i++) {
        ipad[i] = kb[i] ^ 0x36;
        opad[i] = kb[i] ^ 0x5C;
    }
    Ctx c;
    Init(c);
    Update(c, ipad, 64);
    Update(c, msg, mlen);
    uint8_t inner[32];
    Final(c, inner);
    Init(c);
    Update(c, opad, 64);
    Update(c, inner, 32);
    std::vector<uint8_t> out(32);
    Final(c, out.data());
    return out;
}

uint32_t Crc32(const uint8_t* data, size_t len) {
    static uint32_t table[256];
    static bool built = false;
    if (!built) {
        for (uint32_t i = 0; i < 256; i++) {
            uint32_t c = i;
            for (int j = 0; j < 8; j++) c = (c & 1) ? (0xEDB88320u ^ (c >> 1)) : (c >> 1);
            table[i] = c;
        }
        built = true;
    }
    uint32_t crc = 0xFFFFFFFFu;
    for (size_t i = 0; i < len; i++) crc = table[(crc ^ data[i]) & 0xFF] ^ (crc >> 8);
    return crc ^ 0xFFFFFFFFu;
}

// CTR keystream over a raw 32-byte key (v3 envelope path).
void KeystreamRaw(const uint8_t* key32, uint8_t* out, size_t len) {
    uint32_t ctr = 0;
    size_t pos = 0;
    while (pos < len) {
        Ctx c;
        Init(c);
        Update(c, key32, 32);
        uint8_t cb[4] = {(uint8_t)(ctr >> 24), (uint8_t)(ctr >> 16),
                         (uint8_t)(ctr >> 8), (uint8_t)ctr};
        Update(c, cb, 4);
        uint8_t d[32];
        Final(c, d);
        size_t take = len - pos < 32 ? len - pos : 32;
        memcpy(out + pos, d, take);
        pos += take;
        ctr++;
    }
}

// PBKDF2-HMAC-SHA256 -> dkLen bytes (callers use 64: enc[0..32) + auth[32..64)).
std::vector<uint8_t> Pbkdf2(const uint8_t* pw, size_t pwLen,
                             const uint8_t* salt, size_t saltLen,
                             uint32_t iter, size_t dkLen) {
    std::vector<uint8_t> dk;
    dk.reserve(dkLen);
    uint32_t blocks = (uint32_t)((dkLen + 31) / 32);
    for (uint32_t b = 1; b <= blocks; b++) {
        uint8_t be[4] = {(uint8_t)(b >> 24), (uint8_t)(b >> 16),
                         (uint8_t)(b >> 8), (uint8_t)b};
        std::vector<uint8_t> msg;
        msg.insert(msg.end(), salt, salt + saltLen);
        msg.insert(msg.end(), be, be + 4);
        std::vector<uint8_t> u = Hmac(pw, pwLen, msg.data(), msg.size());
        std::vector<uint8_t> t = u;
        for (uint32_t i = 1; i < iter; i++) {
            u = Hmac(pw, pwLen, u.data(), u.size());
            for (size_t j = 0; j < 32; j++) t[j] ^= u[j];
        }
        dk.insert(dk.end(), t.begin(), t.end());
    }
    dk.resize(dkLen);
    return dk;
}

}  // namespace sha
}  // namespace stego
// ---- codec.cpp ----
// codec.cpp — header, scatter placement, LSB engine, CRC helpers.
// Splits exactly per docs/FORMAT.md. PRNG must match python/stegolib.py
// bit-for-bit (golden vectors in tests/vectors/).
#include <stdint.h>

namespace stego {
namespace sha {
std::vector<uint8_t> Hash(const uint8_t* data, size_t len);
void Keystream(const std::string& pw, uint8_t* out, size_t len);
std::vector<uint8_t> Hmac(const uint8_t* key, size_t klen,
                           const uint8_t* msg, size_t mlen);
uint32_t Crc32(const uint8_t* data, size_t len);
}  // namespace sha

namespace codec {

void PutU16(std::vector<uint8_t>& b, uint16_t v) {
    b.push_back((uint8_t)v);
    b.push_back((uint8_t)(v >> 8));
}

void PutU32(std::vector<uint8_t>& b, uint32_t v) {
    for (int i = 0; i < 4; i++) b.push_back((uint8_t)(v >> (i * 8)));
}

// splitmix64 -> xorshift128+ (matches python/stegolib.py exactly).
static uint64_t Splitmix64(uint64_t& s) {
    uint64_t z = (s += 0x9E3779B97F4A7C15ull);
    z = (z ^ (z >> 30)) * 0xBF58476D1CE4E5B9ull;
    z = (z ^ (z >> 27)) * 0x94D049BB133111EBull;
    return z ^ (z >> 31);
}

struct Xor128 {
    uint64_t s[2];
    explicit Xor128(uint64_t seed) {
        uint64_t t = seed;
        s[0] = Splitmix64(t);
        s[1] = Splitmix64(t);
        if (s[0] == 0 && s[1] == 0) s[1] = 0x9E3779B97F4A7C15ull;
    }
    uint64_t Next() {
        uint64_t x = s[0], y = s[1];
        s[0] = y;
        x ^= x << 23;
        s[1] = x ^ y ^ (x >> 17) ^ (y >> 26);
        return s[1] + y;
    }
};

// Placement order for nPx pixels: identity when seed==0, else Fisher-Yates
// with Xor128 draws (j = Next() % (i+1), walking i from n-1 down).
std::vector<uint32_t> Placement(uint32_t nPx, uint32_t seed) {
    std::vector<uint32_t> p(nPx);
    for (uint32_t i = 0; i < nPx; i++) p[i] = i;
    if (seed != 0 && nPx > 1) {
        Xor128 r(seed);
        for (uint32_t i = nPx - 1; i > 0; i--) {
            uint32_t j = (uint32_t)(r.Next() % (i + 1));
            uint32_t t = p[i];
            p[i] = p[j];
            p[j] = t;
        }
    }
    return p;
}

// Placement over pixel range [base, base+count): same shuffle, offset ids.
// Header pixels [0,75) are always sequential; body uses PlacementRange.
std::vector<uint32_t> PlacementRange(uint32_t base, uint32_t count,
                                            uint32_t seed) {
    std::vector<uint32_t> p(count);
    for (uint32_t i = 0; i < count; i++) p[i] = base + i;
    if (seed != 0 && count > 1) {
        Xor128 r(seed);
        for (uint32_t i = count - 1; i > 0; i--) {
            uint32_t j = (uint32_t)(r.Next() % (i + 1));
            uint32_t t = p[i];
            p[i] = p[j];
            p[j] = t;
        }
    }
    return p;
}

// Set bit k of the bitstream into image (3 bits per pixel, R,G,B order).
void PutBit(std::vector<uint8_t>& rgb, uint32_t w,
                   const std::vector<uint32_t>& place, size_t k, int bit) {
    uint32_t p = place[k / 3];
    uint32_t y = p / w, x = p % w;
    uint8_t& ch = rgb[(y * w + x) * 3 + (k % 3)];
    ch = (uint8_t)((ch & 0xFE) | (bit & 1));
}

int GetBit(const std::vector<uint8_t>& rgb, uint32_t w,
                  const std::vector<uint32_t>& place, size_t k) {
    uint32_t p = place[k / 3];
    uint32_t y = p / w, x = p % w;
    return rgb[(y * w + x) * 3 + (k % 3)] & 1;
}

}  // namespace codec
}  // namespace stego
// ---- api.cpp ----
// api.cpp — Encode (v3) / Decode (v3 + v2-legacy + v1-legacy) + C ABI.

namespace stego {
namespace sha {
std::vector<uint8_t> Hash(const uint8_t* data, size_t len);
void Keystream(const std::string& pw, uint8_t* out, size_t len);
void KeystreamRaw(const uint8_t* key32, uint8_t* out, size_t len);
std::vector<uint8_t> Hmac(const uint8_t* key, size_t klen,
                           const uint8_t* msg, size_t mlen);
std::vector<uint8_t> Pbkdf2(const uint8_t* pw, size_t pwLen,
                             const uint8_t* salt, size_t saltLen,
                             uint32_t iter, size_t dkLen);
uint32_t Crc32(const uint8_t* data, size_t len);
}  // namespace sha
namespace codec {
void PutU16(std::vector<uint8_t>& b, uint16_t v);
void PutU32(std::vector<uint8_t>& b, uint32_t v);
std::vector<uint32_t> Placement(uint32_t nPx, uint32_t seed);
std::vector<uint32_t> PlacementRange(uint32_t base, uint32_t count,
                                     uint32_t seed);
void PutBit(std::vector<uint8_t>& rgb, uint32_t w,
            const std::vector<uint32_t>& place, size_t k, int bit);
int GetBit(const std::vector<uint8_t>& rgb, uint32_t w,
           const std::vector<uint32_t>& place, size_t k);
}  // namespace codec

const char* Version() { return "2.0.0"; }

size_t Capacity(uint32_t w, uint32_t h) {
    // v3: 118 header pixels reserved; body must fit data_crc32 (+tag).
    size_t nPx = (size_t)w * h;
    if (nPx <= STEGO_HEADER_V3_PX) return 0;
    size_t bodyBits = (nPx - STEGO_HEADER_V3_PX) * 3;
    if (bodyBits < 4 * 8) return 0;
    return (bodyBits - 4 * 8) / 8;
}

static uint16_t FlagsOf(const Options& o) {
    uint16_t f = 0;
    if (o.compress) f |= STEGO_F_COMPRESS;
    if (o.scatter || o.seed != 0) f |= STEGO_F_SCATTER;
    if (!o.password.empty()) f |= STEGO_F_ENCRYPT;
    if (o.auth) f |= STEGO_F_AUTH;
    return f;
}

// Bounds-checked bitstream read under an explicit placement.
static bool ReadStream(const Image& img, const std::vector<uint32_t>& place,
                       size_t placeBits, size_t bitOff, uint8_t* dst, size_t len) {
    if (len * 8 > placeBits || bitOff + len * 8 > placeBits) return false;
    memset(dst, 0, len);
    for (size_t i = 0; i < len * 8; i++) {
        if (codec::GetBit(img.rgb, img.w, place, bitOff + i)) {
            dst[i / 8] |= (uint8_t)(1 << (i % 8));
        }
    }
    return true;
}

bool Encode(const Image& cover, const uint8_t* payload, size_t payloadLen,
            const Options& opt, Image& out) {
    if (!payload || payloadLen == 0 || cover.w == 0 || cover.h == 0) return false;
    if (cover.rgb.size() < (size_t)cover.w * cover.h * 3) return false;
    if (opt.compress) return false;  // backend deferred (see FORMAT.md)
    if (opt.auth && opt.password.empty()) return false;
    if (opt.scatter && opt.seed == 0) return false;

    // Salt + KDF (v3): PBKDF2 -> 64B (enc[0..32) + auth[32..64)).
    uint8_t salt[STEGO_SALT_LEN] = {0};
    std::vector<uint8_t> encKey, authKey;
    if (!opt.password.empty()) {
        std::random_device rd;
        for (size_t i = 0; i < sizeof(salt); i++) salt[i] = (uint8_t)rd();
        std::vector<uint8_t> dk = sha::Pbkdf2(
            (const uint8_t*)opt.password.data(), opt.password.size(),
            salt, sizeof(salt), STEGO_PBKDF2_ITER, STEGO_PBKDF2_OUT);
        encKey.assign(dk.begin(), dk.begin() + 32);
        authKey.assign(dk.begin() + 32, dk.end());
    }

    // Stage 1+2: (compress n/a) + encrypt (CTR over enc-key).
    std::vector<uint8_t> body(payload, payload + payloadLen);
    if (!opt.password.empty()) {
        std::vector<uint8_t> ks(body.size());
        sha::KeystreamRaw(encKey.data(), ks.data(), ks.size());
        for (size_t i = 0; i < body.size(); i++) body[i] ^= ks[i];
    }

    // v3 header (44 bytes).
    std::vector<uint8_t> hdr;
    hdr.push_back(STEGO_MAGIC_0);
    hdr.push_back(STEGO_MAGIC_1);
    hdr.push_back(STEGO_MAGIC_2);
    hdr.push_back(STEGO_MAGIC_3);
    codec::PutU16(hdr, STEGO_FORMAT_VERSION);
    codec::PutU16(hdr, FlagsOf(opt));
    codec::PutU32(hdr, opt.seed);
    codec::PutU32(hdr, (uint32_t)payloadLen);
    codec::PutU32(hdr, (uint32_t)body.size());
    codec::PutU32(hdr, 0);
    hdr.insert(hdr.end(), salt, salt + sizeof(salt));
    uint32_t hcrc = sha::Crc32(hdr.data(), 40);
    codec::PutU32(hdr, hcrc);

    // Bit source: header + body + data_crc32 [+ hmac over header+ciphertext].
    std::vector<uint8_t> src = hdr;
    src.insert(src.end(), body.begin(), body.end());
    uint32_t dcrc = sha::Crc32(payload, payloadLen);
    size_t dcrcPos = src.size();
    for (int i = 0; i < 4; i++) src.push_back(0);
    src[dcrcPos] = (uint8_t)dcrc;
    src[dcrcPos + 1] = (uint8_t)(dcrc >> 8);
    src[dcrcPos + 2] = (uint8_t)(dcrc >> 16);
    src[dcrcPos + 3] = (uint8_t)(dcrc >> 24);
    if (opt.auth) {
        // NOTE: tag covers header[0..44) + ciphertext ONLY (not data_crc32);
        // decode verifies the identical span. Order matters.
        std::vector<uint8_t> m = sha::Hmac(authKey.data(), authKey.size(),
                                           src.data(), 44 + body.size());
        src.insert(src.end(), m.begin(), m.end());
    }

    size_t needBits = src.size() * 8;
    const size_t kHeaderBits = STEGO_HEADER_V3_LEN * 8;
    const uint32_t kHeaderPx = STEGO_HEADER_V3_PX;
    uint32_t nPx = cover.w * cover.h;
    if (nPx <= kHeaderPx) return false;
    if (needBits < kHeaderBits || needBits - kHeaderBits > ((size_t)nPx - kHeaderPx) * 3) {
        return false;
    }

    out.w = cover.w;
    out.h = cover.h;
    out.rgb = cover.rgb;
    {
        std::vector<uint32_t> seq = codec::Placement(nPx, 0);
        for (size_t k = 0; k < kHeaderBits; k++) {
            int bit = (src[k / 8] >> (k % 8)) & 1;
            codec::PutBit(out.rgb, cover.w, seq, k, bit);
        }
    }
    {
        std::vector<uint32_t> bodyPlace = codec::PlacementRange(
            kHeaderPx, nPx - kHeaderPx, opt.seed);
        for (size_t k = kHeaderBits; k < needBits; k++) {
            int bit = (src[k / 8] >> (k % 8)) & 1;
            codec::PutBit(out.rgb, cover.w, bodyPlace, k - kHeaderBits, bit);
        }
    }
    return true;
}

// --- v3 decode (44B header, PBKDF2 envelope) ---
static bool DecodeV3(const Image& img, const uint8_t* hdr,
                     const std::string& password, std::vector<uint8_t>& out) {
    uint16_t flags = (uint16_t)(hdr[6] | (hdr[7] << 8));
    uint32_t seed = (uint32_t)hdr[8] | ((uint32_t)hdr[9] << 8) |
                    ((uint32_t)hdr[10] << 16) | ((uint32_t)hdr[11] << 24);
    uint32_t orig = (uint32_t)hdr[12] | ((uint32_t)hdr[13] << 8) |
                    ((uint32_t)hdr[14] << 16) | ((uint32_t)hdr[15] << 24);
    uint32_t comp = (uint32_t)hdr[16] | ((uint32_t)hdr[17] << 8) |
                    ((uint32_t)hdr[18] << 16) | ((uint32_t)hdr[19] << 24);
    const uint8_t* salt = hdr + 24;  // v3 salt field (bytes [24..40))
    uint32_t hcrc = (uint32_t)hdr[40] | ((uint32_t)hdr[41] << 8) |
                    ((uint32_t)hdr[42] << 16) | ((uint32_t)hdr[43] << 24);
    if (stego::sha::Crc32(hdr, 40) != hcrc) return false;
    if (flags & STEGO_F_COMPRESS) return false;
    bool enc = (flags & STEGO_F_ENCRYPT) != 0;
    bool auth = (flags & STEGO_F_AUTH) != 0;
    if ((enc || auth) && password.empty()) return false;
    if (auth && !enc) return false;
    if (comp == 0) return false;

    std::vector<uint8_t> encKey, authKey;
    if (enc) {
        std::vector<uint8_t> dk = stego::sha::Pbkdf2(
            (const uint8_t*)password.data(), password.size(),
            salt, STEGO_SALT_LEN, STEGO_PBKDF2_ITER, STEGO_PBKDF2_OUT);
        encKey.assign(dk.begin(), dk.begin() + 32);
        authKey.assign(dk.begin() + 32, dk.end());
    }

    uint32_t nPx = img.w * img.h;
    if (nPx <= STEGO_HEADER_V3_PX) return false;
    size_t bodyBits = ((size_t)nPx - STEGO_HEADER_V3_PX) * 3;
    std::vector<uint32_t> place =
        stego::codec::PlacementRange(STEGO_HEADER_V3_PX, nPx - STEGO_HEADER_V3_PX, seed);

    std::vector<uint8_t> body(comp);
    auto readBody = [&](size_t bitOff, uint8_t* dst, size_t len) -> bool {
        return ReadStream(img, place, bodyBits, bitOff, dst, len);
    };
    if (!readBody(0, body.data(), comp)) return false;

    const size_t kCrcBit = (size_t)comp * 8;
    const size_t kTagBit = ((size_t)comp + 4) * 8;
    std::vector<uint8_t> stored;
    stored.reserve(44 + comp);
    stored.insert(stored.end(), hdr, hdr + 44);
    stored.insert(stored.end(), body.begin(), body.end());
    if (auth) {
        uint8_t tag[32];
        if (!readBody(kTagBit, tag, 32)) return false;
        std::vector<uint8_t> m = stego::sha::Hmac(
            authKey.data(), authKey.size(), stored.data(), stored.size());
        if (memcmp(m.data(), tag, 32) != 0) return false;
    }
    if (enc) {
        std::vector<uint8_t> ks(comp);
        stego::sha::KeystreamRaw(encKey.data(), ks.data(), ks.size());
        for (size_t i = 0; i < comp; i++) body[i] ^= ks[i];
    }
    uint8_t cb[4];
    if (!readBody(kCrcBit, cb, 4)) return false;
    uint32_t dcrc = (uint32_t)cb[0] | ((uint32_t)cb[1] << 8) |
                    ((uint32_t)cb[2] << 16) | ((uint32_t)cb[3] << 24);
    if (orig != comp) return false;
    if (stego::sha::Crc32(body.data(), body.size()) != dcrc) return false;
    out.swap(body);
    return true;
}

// --- v2 decode (28B header, raw-password CTR + domain authkey; read-only) ---
static bool DecodeV2(const Image& img, const uint8_t* hdr,
                     const std::string& password, std::vector<uint8_t>& out) {
    uint16_t flags = (uint16_t)(hdr[6] | (hdr[7] << 8));
    uint32_t seed = (uint32_t)hdr[8] | ((uint32_t)hdr[9] << 8) |
                    ((uint32_t)hdr[10] << 16) | ((uint32_t)hdr[11] << 24);
    uint32_t orig = (uint32_t)hdr[12] | ((uint32_t)hdr[13] << 8) |
                    ((uint32_t)hdr[14] << 16) | ((uint32_t)hdr[15] << 24);
    uint32_t comp = (uint32_t)hdr[16] | ((uint32_t)hdr[17] << 8) |
                    ((uint32_t)hdr[18] << 16) | ((uint32_t)hdr[19] << 24);
    uint32_t hcrc = (uint32_t)hdr[24] | ((uint32_t)hdr[25] << 8) |
                    ((uint32_t)hdr[26] << 16) | ((uint32_t)hdr[27] << 24);
    if (stego::sha::Crc32(hdr, 24) != hcrc) return false;
    if (flags & STEGO_F_COMPRESS) return false;
    bool enc = (flags & STEGO_F_ENCRYPT) != 0;
    bool auth = (flags & STEGO_F_AUTH) != 0;
    if ((enc || auth) && password.empty()) return false;
    if (auth && !enc) return false;
    if (comp == 0) return false;

    uint32_t nPx = img.w * img.h;
    if (nPx <= 75) return false;
    size_t bodyBits = ((size_t)nPx - 75) * 3;
    std::vector<uint32_t> place =
        stego::codec::PlacementRange(75, nPx - 75, seed);

    std::vector<uint8_t> body(comp);
    auto readBody = [&](size_t bitOff, uint8_t* dst, size_t len) -> bool {
        return ReadStream(img, place, bodyBits, bitOff, dst, len);
    };
    if (!readBody(0, body.data(), comp)) return false;

    const size_t kCrcBit = (size_t)comp * 8;
    const size_t kTagBit = ((size_t)comp + 4) * 8;
    std::vector<uint8_t> stored;
    stored.reserve(28 + comp);
    stored.insert(stored.end(), hdr, hdr + 28);
    stored.insert(stored.end(), body.begin(), body.end());
    if (auth) {
        uint8_t tag[32];
        if (!readBody(kTagBit, tag, 32)) return false;
        std::string ak = std::string("stego-auth-v2") + password;
        std::vector<uint8_t> h =
            stego::sha::Hash((const uint8_t*)ak.data(), ak.size());
        std::vector<uint8_t> m =
            stego::sha::Hmac(h.data(), h.size(), stored.data(), stored.size());
        if (memcmp(m.data(), tag, 32) != 0) return false;
    }
    if (enc) {
        std::vector<uint8_t> ks(comp);
        stego::sha::Keystream(password, ks.data(), ks.size());
        for (size_t i = 0; i < comp; i++) body[i] ^= ks[i];
    }
    uint8_t cb[4];
    if (!readBody(kCrcBit, cb, 4)) return false;
    uint32_t dcrc = (uint32_t)cb[0] | ((uint32_t)cb[1] << 8) |
                    ((uint32_t)cb[2] << 16) | ((uint32_t)cb[3] << 24);
    if (orig != comp) return false;
    if (stego::sha::Crc32(body.data(), body.size()) != dcrc) return false;
    out.swap(body);
    return true;
}

bool Decode(const Image& img, const std::string& password,
            std::vector<uint8_t>& out) {
    out.clear();
    if (img.w == 0 || img.h == 0) return false;
    if (img.rgb.size() < (size_t)img.w * img.h * 3) return false;
    size_t totalBits = (size_t)img.w * img.h * 3;

    // v3 header attempt (44 bytes, sequential pixels [0,118)).
    uint8_t hdr3[STEGO_HEADER_V3_LEN];
    {
        std::vector<uint32_t> seq = codec::Placement(img.w * img.h, 0);
        if (ReadStream(img, seq, totalBits, 0, hdr3, sizeof(hdr3))) {
            if (hdr3[0] == STEGO_MAGIC_0 && hdr3[1] == STEGO_MAGIC_1 &&
                hdr3[2] == STEGO_MAGIC_2 && hdr3[3] == STEGO_MAGIC_3) {
                uint16_t ver = (uint16_t)(hdr3[4] | (hdr3[5] << 8));
                if (ver == STEGO_FORMAT_VERSION) {
                    if (DecodeV3(img, hdr3, password, out)) return true;
                    return false;  // valid v3 header that fails = reject
                }
            }
        }
    }

    // v2 header attempt (28 bytes, read-only legacy path).
    uint8_t hdr[28];
    {
        std::vector<uint32_t> seq = codec::Placement(img.w * img.h, 0);
        if (ReadStream(img, seq, totalBits, 0, hdr, sizeof(hdr))) {
            if (hdr[0] == STEGO_MAGIC_0 && hdr[1] == STEGO_MAGIC_1 &&
                hdr[2] == STEGO_MAGIC_2 && hdr[3] == STEGO_MAGIC_3) {
                uint16_t ver = (uint16_t)(hdr[4] | (hdr[5] << 8));
                if (ver == 0x0002) {
                    if (DecodeV2(img, hdr, password, out)) return true;
                    return false;
                }
            }
        }
    }

    // Legacy v1 path (deprecated read-only): [u32 size][payload], sequential.
    uint8_t szb[4];
    {
        std::vector<uint32_t> seq = codec::Placement(img.w * img.h, 0);
        if (!ReadStream(img, seq, totalBits, 0, szb, 4)) return false;
        uint32_t size = (uint32_t)szb[0] | ((uint32_t)szb[1] << 8) |
                        ((uint32_t)szb[2] << 16) | ((uint32_t)szb[3] << 24);
        if (size == 0 || size > totalBits / 8) return false;
        out.resize(size);
        if (!ReadStream(img, seq, totalBits, 32, out.data(), size)) {
            out.clear();
            return false;
        }
    }
    return true;
}

}  // namespace stego

// --- C ABI ---
extern "C" {

int stego_encode(const stego_image_t* cover, const uint8_t* payload,
                 size_t payload_len, const stego_options_t* opt,
                 uint8_t* out_rgb) {
    if (!cover || !payload || !opt || !out_rgb) return STEGO_C_ERR_PARAM;
    stego::Image c;
    c.w = cover->w;
    c.h = cover->h;
    c.rgb.assign(cover->rgb, cover->rgb + (size_t)cover->w * cover->h * 3);
    stego::Options o;
    o.compress = opt->compress != 0;
    o.scatter = opt->scatter != 0;
    o.seed = opt->seed;
    if (opt->password) o.password = opt->password;
    o.auth = opt->auth != 0;
    stego::Image res;
    if (!stego::Encode(c, payload, payload_len, o, res)) {
        return (o.compress || (o.auth && o.password.empty())) ? STEGO_C_ERR_UNSUPPORTED
                                                              : STEGO_C_ERR_CAPACITY;
    }
    memcpy(out_rgb, res.rgb.data(), res.rgb.size());
    return STEGO_C_OK;
}

int stego_decode(const stego_image_t* img, const char* password,
                 uint8_t** out, size_t* out_len) {
    if (!img || !out || !out_len) return STEGO_C_ERR_PARAM;
    stego::Image c;
    c.w = img->w;
    c.h = img->h;
    c.rgb.assign(img->rgb, img->rgb + (size_t)img->w * img->h * 3);
    std::vector<uint8_t> res;
    if (!stego::Decode(c, password ? password : "", res)) return STEGO_C_ERR_FORMAT;
    *out = (uint8_t*)malloc(res.size() ? res.size() : 1);
    if (!*out) return STEGO_C_ERR_PARAM;
    memcpy(*out, res.data(), res.size());
    *out_len = res.size();
    return STEGO_C_OK;
}

void stego_free(void* p) { free(p); }
const char* stego_version(void) { return stego::Version(); }

}  // extern "C"
#endif // STEGO_IMPLEMENTATION
